 version: '2'
 services:
  mongodb:
    container_name: 'mongodb'
    restart: unless-stopped
    image: mongo:latest
    ports:
      - "27017:27107"

  api:
    restart: unless-stopped
    image: api:latest
    command: python /code/manage.py runserver 0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - ".:/code/"
    depends_on:
      - mongodb
    environment:
      - DB_PORT=27017
      - API_PORT=5000
      - DB_HOST=mongodb
      - API_HOST=api
      - DB_NAME=PersonDB
